// <auto-generated />
using EstadisticDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstadisticDataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EstadisticDomain.Estadistic", b =>
                {
                    b.Property<int>("ID_E")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name_E")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID_E");

                    b.ToTable("Estadistics");

                    b.HasData(
                        new
                        {
                            ID_E = 1,
                            Name_E = "Anual"
                        },
                        new
                        {
                            ID_E = 2,
                            Name_E = "Mensual"
                        },
                        new
                        {
                            ID_E = 3,
                            Name_E = "Diaria"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
