// <auto-generated />
using CinemaDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaDataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210215094626_CinemaMig")]
    partial class CinemaMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CinemaDomain.Cinema", b =>
                {
                    b.Property<int>("ID_Cinema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count_Armchair")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID_Cinema");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            ID_Cinema = 1,
                            Count_Armchair = 100
                        },
                        new
                        {
                            ID_Cinema = 2,
                            Count_Armchair = 108
                        },
                        new
                        {
                            ID_Cinema = 3,
                            Count_Armchair = 99
                        },
                        new
                        {
                            ID_Cinema = 4,
                            Count_Armchair = 57
                        },
                        new
                        {
                            ID_Cinema = 5,
                            Count_Armchair = 128
                        },
                        new
                        {
                            ID_Cinema = 6,
                            Count_Armchair = 133
                        },
                        new
                        {
                            ID_Cinema = 7,
                            Count_Armchair = 98
                        },
                        new
                        {
                            ID_Cinema = 8,
                            Count_Armchair = 99
                        },
                        new
                        {
                            ID_Cinema = 9,
                            Count_Armchair = 83
                        },
                        new
                        {
                            ID_Cinema = 10,
                            Count_Armchair = 99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
