// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintDataBase;

namespace PrintDataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PrintDomain.Printer", b =>
                {
                    b.Property<int>("ID_Printer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Printer");

                    b.ToTable("Printers");

                    b.HasData(
                        new
                        {
                            ID_Printer = 1,
                            PrinterName = "Adobe PDF"
                        },
                        new
                        {
                            ID_Printer = 2,
                            PrinterName = "Fax"
                        },
                        new
                        {
                            ID_Printer = 3,
                            PrinterName = "Microsoft XPS Document Writer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
