// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PunctuationDataBase;

namespace PunctuationDataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210616065632_PunctuationMig")]
    partial class PunctuationMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PunctuationDomain.Punctuation", b =>
                {
                    b.Property<int>("ID_M")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID_M", "Email");

                    b.ToTable("PunctuationsMovies");

                    b.HasData(
                        new
                        {
                            ID_M = 7,
                            Email = "grettelhernandezmatcom@gmail.com",
                            Points = 5
                        },
                        new
                        {
                            ID_M = 2,
                            Email = "melissa.sanchez@gmail.com",
                            Points = 4
                        },
                        new
                        {
                            ID_M = 2,
                            Email = "grettelhernandezmatcom@gmail.com",
                            Points = 5
                        },
                        new
                        {
                            ID_M = 3,
                            Email = "melissa.sanchez@gmail.com",
                            Points = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
