// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgrammingDataBase;

namespace ProgrammingDataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210617041953_ProgrammingMig")]
    partial class ProgrammingMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProgrammingDomain.Models.Programming", b =>
                {
                    b.Property<int>("ID_M")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_Cinema")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataHour_P")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pay_Points")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Ticket_Price")
                        .HasColumnType("REAL");

                    b.HasKey("ID_M", "ID_Cinema", "DataHour_P");

                    b.ToTable("Programming");

                    b.HasData(
                        new
                        {
                            ID_M = 1,
                            ID_Cinema = 3,
                            DataHour_P = "14-06-2021 12:40",
                            Pay_Points = 8,
                            Ticket_Price = 15f
                        },
                        new
                        {
                            ID_M = 8,
                            ID_Cinema = 1,
                            DataHour_P = "14-06-2021 10:30",
                            Pay_Points = 5,
                            Ticket_Price = 10f
                        },
                        new
                        {
                            ID_M = 2,
                            ID_Cinema = 3,
                            DataHour_P = "14-06-2021 10:30",
                            Pay_Points = 5,
                            Ticket_Price = 10f
                        },
                        new
                        {
                            ID_M = 4,
                            ID_Cinema = 3,
                            DataHour_P = "14-06-2021 08:30",
                            Pay_Points = 2,
                            Ticket_Price = 7.2f
                        },
                        new
                        {
                            ID_M = 5,
                            ID_Cinema = 9,
                            DataHour_P = "15-06-2021 20:00",
                            Pay_Points = 11,
                            Ticket_Price = 21f
                        },
                        new
                        {
                            ID_M = 10,
                            ID_Cinema = 5,
                            DataHour_P = "16-06-2021 09:40",
                            Pay_Points = 4,
                            Ticket_Price = 8.4f
                        },
                        new
                        {
                            ID_M = 10,
                            ID_Cinema = 7,
                            DataHour_P = "16-06-2021 09:40",
                            Pay_Points = 6,
                            Ticket_Price = 12f
                        },
                        new
                        {
                            ID_M = 8,
                            ID_Cinema = 5,
                            DataHour_P = "17-06-2021 2:20",
                            Pay_Points = 4,
                            Ticket_Price = 12.5f
                        },
                        new
                        {
                            ID_M = 3,
                            ID_Cinema = 6,
                            DataHour_P = "17-06-2021 2:20",
                            Pay_Points = 13,
                            Ticket_Price = 25f
                        },
                        new
                        {
                            ID_M = 7,
                            ID_Cinema = 7,
                            DataHour_P = "19-06-2021 11:30",
                            Pay_Points = 5,
                            Ticket_Price = 10f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
