// <auto-generated />
using BookingDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingDataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BookingDomain.Booking", b =>
                {
                    b.Property<int>("ID_M")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_Cinema")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataHour_P")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email_User")
                        .HasColumnType("TEXT");

                    b.Property<string>("Buy_Cod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataHour_Booking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsPaid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Selected_Armchairs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Total_Money")
                        .HasColumnType("REAL");

                    b.Property<int>("Total_Money_By_Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total_Tickets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total_TicketsStudentsFEU")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total_Tickets_Childrens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total_Tickets_Retired")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID_M", "ID_Cinema", "DataHour_P", "Email_User");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
