// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieDataBase;

namespace MovieDataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MovieDomain.Movie", b =>
                {
                    b.Property<int>("ID_M")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name_P")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.HasKey("ID_M");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            ID_M = 1,
                            Director = "Vicky Jenson",
                            Duration = 90,
                            Genre = "Animación",
                            Name_P = "Shrek I",
                            Photo = "shrek1.jpg",
                            Synopsis = "Shrek es un ogro verde, gruñón y altamente territorial que ama la soledad..."
                        },
                        new
                        {
                            ID_M = 2,
                            Director = "Vicky Jenson",
                            Duration = 93,
                            Genre = "Animación",
                            Name_P = "Shrek II",
                            Photo = "shrek2.jpg",
                            Synopsis = "Tras su luna de miel después de derrotar a lord farquaad en la película anterior , el ogro Shrek y la princesa Fiona regresan a su pantano..."
                        },
                        new
                        {
                            ID_M = 3,
                            Director = "Rob Cohen",
                            Duration = 107,
                            Genre = "Accion",
                            Name_P = "The Fast and the Furious",
                            Photo = "fastfurious1.jpg",
                            Synopsis = "El oficial de policía Brian O'Conner (Paul Walker) es enviado encubierto en una investigación conjunta de la policía de Los Ángeles y el FBI para detener a la banda que se dedica al robo de camiones con mercancía..."
                        },
                        new
                        {
                            ID_M = 4,
                            Director = "Jill Culton",
                            Duration = 97,
                            Genre = "Animación",
                            Name_P = "Abominable",
                            Photo = "abominable.jpg",
                            Synopsis = "Un joven Yeti escapa de un complejo en Shanghái propiedad del rico empresario Burnish (Eddie Izzard), que tiene la intención de usarlo para demostrar la existencia de yetis en el mundo..."
                        },
                        new
                        {
                            ID_M = 5,
                            Director = "Sam Mendes",
                            Duration = 143,
                            Genre = "Acción",
                            Name_P = "Skyfall",
                            Photo = "skyfall.jpg",
                            Synopsis = ""
                        },
                        new
                        {
                            ID_M = 6,
                            Director = "Peter Jackson",
                            Duration = 201,
                            Genre = "Aventuras",
                            Name_P = "El Señor de los Anillos: El Retorno del Rey",
                            Photo = "senoranillos1.jpg",
                            Synopsis = "La historia comienza con un recuerdo de cómo el hobbit Smeágol llegó a poseer el Anillo de Poder, tras matar a su amigo Déagol, quien lo había encontrado en el fondo de un río..."
                        },
                        new
                        {
                            ID_M = 7,
                            Director = "Rich Moore",
                            Duration = 108,
                            Genre = "Animación",
                            Name_P = "Zootopia",
                            Photo = "zootopia.jpg",
                            Synopsis = "En un mundo poblado por animales antropomórficos en donde los humanos nunca existieron, Judy Hopps, una coneja de la ciudad rural de Bunnyburrow, sueña con convertirse en oficial de policía..."
                        },
                        new
                        {
                            ID_M = 8,
                            Director = "James Wan",
                            Duration = 143,
                            Genre = "Acción, Aventura, Fantasía, Superhéroes",
                            Name_P = "Aquaman",
                            Photo = "aquaman.jpg",
                            Synopsis = "En Maine, 1985, el guardián del faro Thomas Curry encuentra y rescata, durante una tormenta, seriamente herida a la princesa del reino submarino Atlantis, Atlanna y la lleva a su casa..."
                        },
                        new
                        {
                            ID_M = 9,
                            Director = "James Cameron",
                            Duration = 162,
                            Genre = "Ciencia ficción",
                            Name_P = "Avatar",
                            Photo = "avatar1.jpg",
                            Synopsis = "La acción se sitúa en 2154. Jake Sully, un marine veterano de guerra y herido en combate que ha quedado parapléjico, es seleccionado para participar en el programa Avatar..."
                        },
                        new
                        {
                            ID_M = 10,
                            Director = "Clay Kaytis",
                            Duration = 97,
                            Genre = "Animación",
                            Name_P = "Angry Birds",
                            Photo = "angrybirds1.jpg",
                            Synopsis = "La Isla Pájaro es una isla habitada por aves que no vuelan, una de ellas Red, un cardenal rojo que es sentenciado por el juez Peckinpah a asistir a sesiones de control de ira, tras perder su temperamento..."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
